### ISSUE TITLE
Why is the payload size `kmalloc_size-0x18` in `do_defragment`?

### ISSUE THREAD

**Issue by Manny684** [chenyueqi/SLAKE#2]
I was checking out how you do your defragmentation and stumbled over the `do_defragment` method in `user_key_payload_tmpl.h`. I noticed that the `plen` parameter of `add_key` is set to `kmalloc_size-0x18` (equalling the payload length). I have trouble understanding this - when I look at the source of the `add_key` system call, it directly passes `plen` to `kvmalloc`. So why do you substract 0x18, instead of directly using the size of the target cache for the allocation?

Thank you in advance for your answer!

**Comment by chenyueqi** [comment]
hey manny684, so nice to hear from you again. The quick answer is the
add_key system call will allocate at least two objects related to payload.
One of them is freed agains before the return of the system call and
another resides on heap. We want to use the latter one for spraying and
this latter has a head the size of which is 0x18. I recommend you to use
ftrace tool to trace down object activity in kernel for debugging.

**Comment by Manny684** [comment]
Thank you again so much for your quick answer!
